<?php
# autogenerated on:2014-07-31 14:40:32 
# by user:Administrator ID:1, try not to hand edit too much
$std_fields['activity_type']=array (
  'id' => 
  array (
    'type' => 'label',
    'name' => 'id',
  ),
  'name' => 
  array (
    'type' => 'text',
    'name' => 'name',
  ),
  'description' => 
  array (
    'type' => 'textarea',
    'name' => 'description',
  ),
  'activity_value' => 
  array (
    'name' => 'activity_value',
    'type' => 'number',
    'value' => '1',
  ),
);
?>