<?php
# autogenerated on:2014-08-25 00:37:09 
# by user:Administrator ID:1, try not to hand edit too much
$std_fields['activity']=array (
  'id' => 
  array (
    'type' => 'label',
    'name' => 'id',
  ),
  'name' => 
  array (
    'type' => 'text',
    'name' => 'name',
  ),
  'activity_type_id' => 
  array (
    'type' => 'number',
    'name' => 'activity_type_id',
  ),
  'activity_status_id' => 
  array (
    'type' => 'number',
    'name' => 'activity_status_id',
  ),
  'is_team_activity' => 
  array (
    'name' => 'is_team_activity',
    'type' => 'list',
    'value' => 'N',
    'options' => 
    array (
      'Y' => 'Y',
      'N' => 'N',
    ),
  ),
  'timer' => 
  array (
    'name' => 'timer',
    'type' => 'number',
    'value' => '120',
    'size'=>'4',
    'maxlength'=>'4',
    'validate'=>'number',
    'required'=>'1',
    'css'=>"\" required  pattern='[0-9]+' type=number"
  ),
);
?>
