<?php
# autogenerated on:2014-08-11 13:37:33 
# by user:Administrator ID:1, try not to hand edit too much
$std_fields['activity2session']=array (
  'id' => 
  array (
    'name' => 'id',
    'type' => 'label',
  ),
  'activity_id' => 
  array (
    'name' => 'activity_id',
  ),
  'session_id' => 
  array (
    'name' => 'session_id',
  ),
);
?>