<?php
# autogenerated on:2014-08-26 21:36:06 
# by user:Administrator ID:1, try not to hand edit too much
$std_fields['completed_activity']=array (
  'id' => 
  array (
    'name' => 'id',
    'type' => 'label',
  ),
  'activity_date' => 
  array (
    'name' => 'activity_date',
    'type' => 'date',
  ),
  'usr_id' => 
  array (
    'name' => 'usr_id',
    'type' => 'number',
    'value' => '1',
  ),
  'activity_id' => 
  array (
    'name' => 'activity_id',
    'type' => 'number',
    'value' => '1',
  ),
  'team' => 
  array (
    'name' => 'team',
    'type' => 'number',
    'value' => '0',
  ),
);
?>