<?php
# autogenerated on:2014-08-19 01:05:46 
# by user:Administrator ID:1, try not to hand edit too much
$std_fields['message']=array (
  'id' => 
  array (
    'name' => 'id',
    'type' => 'label',
  ),
  'source' => 
  array (
    'name' => 'source',
    'type' => 'hidden',
    'value' => ssid(),
    'foreign'=>'usr.name',
  ),
  'destination' => 
  array (
    'name' => 'destination',
    'type' => 'number',
    'value' => '1',
    'foreign'=>'usr.name',
  ),
  'body' => 
  array (
    'name' => 'body',
    'type' => 'textarea',
    'value' => '',
  ),
  'view_date' => 
  array (
    'name' => 'view_date',
    'type' => 'label',
    'value' => '2000-01-01',
  ),
  'creation_date' => 
  array (
    'name' => 'creation_date',
    'type' => 'label',
    'value' => '[#now]',
  ),
);
?>
