<?php
# autogenerated on:2014-08-13 11:20:33 
# by user:Administrator ID:1, try not to hand edit too much
$std_fields['question_option']=array (
  'id' => 
  array (
    'type' => 'label',
    'name' => 'id',
  ),
  'name' => 
  array (
    'type' => 'text',
    'name' => 'name',
  ),
  'question_id' => 
  array (
    'type' => 'number',
    'name' => 'question_id',
  ),
  'is_correct' => 
  array (
    'name' => 'is_correct',
    'type' => 'list',
    'value' => 'N',
    'options' => 
    array (
      'Y' => 'Y',
      'N' => 'N',
    ),
  ),
);
?>