<?php
# autogenerated on:2014-07-31 14:44:52 
# by user:Administrator ID:1, try not to hand edit too much
$std_fields['question']=array (
  'id' => 
  array (
    'type' => 'label',
    'name' => 'id',
  ),
  'name' => 
  array (
    'type' => 'text',
    'name' => 'name',
  ),
  'description' => 
  array (
    'type' => 'textarea',
    'name' => 'description',
  ),
  'activity_id' => 
  array (
    'type' => 'number',
    'name' => 'activity_id',
  ),
  'category_id' => 
  array (
    'name' => 'category_id',
    'type' => 'number',
    'value' => '1',
  ),
);
?>