<?php
# autogenerated on:2014-08-27 07:44:19 
# by user:Administrator ID:1, try not to hand edit too much
$std_fields['user_tutorial']=array (
  'id' => 
  array (
    'name' => 'id',
    'type' => 'label',
  ),
  'name' => 
  array (
    'name' => 'name',
    'type' => 'text',
    'value' => '',
  ),
  'usr_id' => 
  array (
    'name' => 'usr_id',
    'type' => 'number',
    'value' => '1',
  ),
);
?>