<?php
# autogenerated on:2014-07-31 14:47:27 
# by user:Administrator ID:1, try not to hand edit too much
$std_fields['usr2session']=array (
  'id' => 
  array (
    'type' => 'label',
    'name' => 'id',
  ),
  'usr_id' => 
  array (
    'type' => 'number',
    'name' => 'usr_id',
  ),
  'session_id' => 
  array (
    'type' => 'number',
    'name' => 'session_id',
  ),
);
?>