del C:\xampp\htdocs\project0.2.7.6\projects\crmlib3\template\main.html~
del C:\xampp\htdocs\project0.2.7.6\projects\daniel\template\main.html~
del C:\xampp\htdocs\project0.2.7.6\projects\directorio0274\template\main.html~
del C:\xampp\htdocs\project0.2.7.6\projects\directorio0274\template\footer.php~
del C:\xampp\htdocs\project0.2.7.6\projects\directorio0274\template\imagenes\tablas\tabla9.htm~
del C:\xampp\htdocs\project0.2.7.6\projects\directorio0274\template\imagenes\tablas\tabla8.htm~
del C:\xampp\htdocs\project0.2.7.6\projects\directorio0274_2\media\tablas\iframe.htm~
del C:\xampp\htdocs\project0.2.7.6\projects\directorio0274_2\template\main.html~
del C:\xampp\htdocs\project0.2.7.6\projects\directorio0274_2\template\footer.php~
del C:\xampp\htdocs\project0.2.7.6\projects\directorio0274_2\template\contacto\edit_all.template.html~
del C:\xampp\htdocs\project0.2.7.6\projects\directorio0274_2\template\contacto\read_only_view.template.html~
del C:\xampp\htdocs\project0.2.7.6\projects\directorio0274_2\template\imagenes\tablas\tabla9.htm~
del C:\xampp\htdocs\project0.2.7.6\projects\directorio0274_2\template\imagenes\tablas\tabla8.htm~
del C:\xampp\htdocs\project0.2.7.6\projects\EJEMPLOS\boris\template\main.html~
del C:\xampp\htdocs\project0.2.7.6\projects\EJEMPLOS\uni\template\main.html~
del C:\xampp\htdocs\project0.2.7.6\projects\EJEMPLOS\wow\template\main.html~
del C:\xampp\htdocs\project0.2.7.6\projects\events_test\template\main.html~
del C:\xampp\htdocs\project0.2.7.6\projects\examen\template\main.html~
del C:\xampp\htdocs\project0.2.7.6\projects\facturacion\template\main.html~
del C:\xampp\htdocs\project0.2.7.6\projects\GIS_geographical_information_system\gis.php~
del C:\xampp\htdocs\project0.2.7.6\projects\hbmtest74\template\main.html~
del C:\xampp\htdocs\project0.2.7.6\projects\m1\template\main.html~
del C:\xampp\htdocs\project0.2.7.6\projects\media_center\template\main.html~
del C:\xampp\htdocs\project0.2.7.6\projects\olap_centrodiesel\olap_centrodiesel.reporte.php~
del C:\xampp\htdocs\project0.2.7.6\projects\olap_centrodiesel\template\main.html~
del C:\xampp\htdocs\project0.2.7.6\projects\personal1\template\main.html~
del C:\xampp\htdocs\project0.2.7.6\projects\personal2\template\main.html~
del C:\xampp\htdocs\project0.2.7.6\projects\pivot_test\template\main.html~
del C:\xampp\htdocs\project0.2.7.6\projects\pizano\doc\usuario.htm~
del C:\xampp\htdocs\project0.2.7.6\projects\prefix_test\template\main.html~
del C:\xampp\htdocs\project0.2.7.6\projects\process_manager\template\main.html~
del C:\xampp\htdocs\project0.2.7.6\projects\protos\template\main.html~
del C:\xampp\htdocs\project0.2.7.6\projects\protos2\template\main.html~
del C:\xampp\htdocs\project0.2.7.6\projects\registro_de_actividades\template\main.html~
del C:\xampp\htdocs\project0.2.7.6\projects\renault4\template\main.html~
del C:\xampp\htdocs\project0.2.7.6\projects\sales\template\main.html~
del C:\xampp\htdocs\project0.2.7.6\projects\sif\doc\sif.htm~
del C:\xampp\htdocs\project0.2.7.6\projects\sif\tools\view\graph.php~
del C:\xampp\htdocs\project0.2.7.6\projects\sif\tools\view\index.php~
del C:\xampp\htdocs\project0.2.7.6\projects\sif76\doc\editor.htm~
del C:\xampp\htdocs\project0.2.7.6\projects\sif76\scripts_varios\redir.index.php~
del C:\xampp\htdocs\project0.2.7.6\projects\sif76_man\man\pdf_creator.htm~
del C:\xampp\htdocs\project0.2.7.6\projects\sif76_man\man\sif_contabilidad.htm~
del C:\xampp\htdocs\project0.2.7.6\projects\sif76_man\man\sif_forestal.htm~
del C:\xampp\htdocs\project0.2.7.6\projects\sif76_man\man\sif_geografia.htm~
del C:\xampp\htdocs\project0.2.7.6\projects\sif76_man\man\sif_help_main.htm~
del C:\xampp\htdocs\project0.2.7.6\projects\sif76_man\man\sif_ordenes_de_servicio.htm~
del C:\xampp\htdocs\project0.2.7.6\projects\sif76_man\man\sif_reportes.htm~
del C:\xampp\htdocs\project0.2.7.6\projects\sif76_man\man\sif_seguridad.htm~
del C:\xampp\htdocs\project0.2.7.6\projects\sqlobjects\doc\description.html~
del C:\xampp\htdocs\project0.2.7.6\projects\system5\controller\faq.controller.php~
del C:\xampp\htdocs\project0.2.7.6\projects\system5\model\por_hacer.model.php~
del C:\xampp\htdocs\project0.2.7.6\projects\system5\template\main.html~
del C:\xampp\htdocs\project0.2.7.6\projects\system5\view\por_hacer.view.php~
del C:\xampp\htdocs\project0.2.7.6\projects\system5\view\por_hacer\list_all_copy.view.php~
del C:\xampp\htdocs\project0.2.7.6\projects\tagtest\template\main.html~
del C:\xampp\htdocs\project0.2.7.6\projects\tag_test\template\main.html~
del C:\xampp\htdocs\project0.2.7.6\projects\test1\template\main.html~
del C:\xampp\htdocs\project0.2.7.6\projects\tsift\template\main.html~
del C:\xampp\htdocs\project0.2.7.6\projects\untested\1sif\doc\sif.htm~
del C:\xampp\htdocs\project0.2.7.6\projects\untested\1sif\tools\view\graph.php~
del C:\xampp\htdocs\project0.2.7.6\projects\untested\1sif\tools\view\index.php~
del C:\xampp\htdocs\project0.2.7.6\projects\untested\noti2007\i18n\ES\noticia.i18n.php~
del C:\xampp\htdocs\project0.2.7.6\projects\untested\noti2007\templates\noticias.html~
del C:\xampp\htdocs\project0.2.7.6\projects\untested\noti2007\templates\profesiones.html~
del C:\xampp\htdocs\project0.2.7.6\projects\untested\noti2007\view\noticia\list_all_copy.view.php~
del C:\xampp\htdocs\project0.2.7.6\projects\untested\novedades\wink\convertir_un_archivo_a_csv.htm~
del C:\xampp\htdocs\project0.2.7.6\projects\untested\railgun\include\footer.php~
del C:\xampp\htdocs\project0.2.7.6\projects\untested\sif.template\media\user.css~
del C:\xampp\htdocs\project0.2.7.6\projects\untested\sif.template\template\main.html~
del C:\xampp\htdocs\project0.2.7.6\projects\untested\sif.template\template\footer.php~
del C:\xampp\htdocs\project0.2.7.6\projects\untested\sif.template\template\contacto\edit_all.template.html~
del C:\xampp\htdocs\project0.2.7.6\projects\untested\sif.template\template\contacto\read_only_view.template.html~
del C:\xampp\htdocs\project0.2.7.6\projects\untested\sif.template\template\imagenes\tablas\tabla9.htm~
del C:\xampp\htdocs\project0.2.7.6\projects\untested\sif.template\template\imagenes\tablas\tabla8.htm~
del C:\xampp\htdocs\project0.2.7.6\projects\untested\vendedor400\std.php~
del C:\xampp\htdocs\project0.2.7.6\projects\untested\videos\doc\por hacer.txt~
del C:\xampp\htdocs\project0.2.7.6\projects\untested\videos\i18n\ES\cliente.i18n.php~
del C:\xampp\htdocs\project0.2.7.6\projects\untested\videos\i18n\ES\estado_pedido.i18n.php~
del C:\xampp\htdocs\project0.2.7.6\projects\untested\videos\i18n\ES\item.i18n.php~
del C:\xampp\htdocs\project0.2.7.6\projects\untested\videos\i18n\ES\pedido.i18n.php~
del C:\xampp\htdocs\project0.2.7.6\projects\untested\videos\i18n\ES\pedido_item.i18n.php~
del C:\xampp\htdocs\project0.2.7.6\projects\untested\videos\install\install2.sql~
del C:\xampp\htdocs\project0.2.7.6\projects\untested\videos\install\patch1.sql~
del C:\xampp\htdocs\project0.2.7.6\projects\vehiculos_web\template\main.html~
del C:\xampp\htdocs\project0.2.7.6\projects\vehiculos_web2\template\main.html~
del C:\xampp\htdocs\project0.2.7.6\projects\WS\lib\class.wsdl.php~
del C:\xampp\htdocs\project0.2.7.6\projects\WS\lib\nusoap.php~
del C:\xampp\htdocs\project0.2.7.6\projects\WS\samples\index.html~
del C:\xampp\htdocs\project0.2.7.6\projects\_deprecated\backup.nov.2007.sif74\doc\ES\editor.htm~
del C:\xampp\htdocs\project0.2.7.6\projects\_deprecated\backup.nov.2007.sif74\template\main.html~
del C:\xampp\htdocs\project0.2.7.6\projects\_useless\aa\template\main.html~
del C:\xampp\htdocs\project0.2.7.6\projects\_useless\darsena\template\main.html~
del C:\xampp\htdocs\project0.2.7.6\projects\_useless\directorio99\template\main.html~
del C:\xampp\htdocs\project0.2.7.6\projects\_useless\items\template\main.html~
del C:\xampp\htdocs\project0.2.7.6\core\shared\templates\main.html~
del C:\xampp\htdocs\project0.2.7.6\core\util\1.html~~
del C:\xampp\htdocs\project0.2.7.6\core\util\js.absolute.position.html~
del C:\xampp\htdocs\project0.2.7.6\core\util\tbl.test.html~~~
del C:\xampp\htdocs\project0.2.7.6\core\util\gen.cfg~
del C:\xampp\htdocs\project0.2.7.6\core\util\minimal.cfg~
del C:\xampp\htdocs\project0.2.7.6\core\util\tbl.test.html~
del C:\xampp\htdocs\project0.2.7.6\core\util\simple.html~~
del C:\xampp\htdocs\project0.2.7.6\core\util\tbody.test.html~
del C:\xampp\htdocs\project0.2.7.6\core\util\1.html~
del C:\xampp\htdocs\project0.2.7.6\core\util\test.css.html~
del C:\xampp\htdocs\project0.2.7.6\core\util\cs.test.html~~
del C:\xampp\htdocs\project0.2.7.6\core\util\cs.test.html~
del C:\xampp\htdocs\project0.2.7.6\core\util\css.test.html~
del C:\xampp\htdocs\project0.2.7.6\core\util\css2.test.html~
del C:\xampp\htdocs\project0.2.7.6\core\util\menu.html~
del C:\xampp\htdocs\project0.2.7.6\core\util\search.html~
del C:\xampp\htdocs\project0.2.7.6\core\util\js.absolute.position.html~~
del C:\xampp\htdocs\project0.2.7.6\core\util\rel.test.html~~
del C:\xampp\htdocs\project0.2.7.6\core\util\rel.test.html~
del C:\xampp\htdocs\project0.2.7.6\core\util\simple.html~
del C:\xampp\htdocs\project0.2.7.6\core\util\tbl.test.html~~
del C:\xampp\htdocs\project0.2.7.6\core\util\1.html~~~
del C:\xampp\htdocs\project0.2.7.6\core\util\css2.test.html~~
del C:\xampp\htdocs\project0.2.7.6\core\util\menu.html~~
del C:\xampp\htdocs\project0.2.7.6\core\util\search.html~~
del C:\xampp\htdocs\project0.2.7.6\core\util\css.test.html~~
