<?php
# autogenerated on:2009-01-03 15:43:06 
# by user:Administrator ID:1, try not to hand edit too much
$std_views['userquery']=array (
	'edit_all' => 
	array (
		'title' => 'edit_table_title',
		'type' => 'record',
		'actions' => 
		array (
			0 => 'all_b2l',
			1 => 'all_run',
			2 => 'all_edit2',
			3 => 'all_delete',
		),
		'fields' => array(
			'id' => 
			array (
				'name' => 'id',
				'type' => 'label',
			),
			'titulo' => 
			array (
				'name' => 'titulo',
			),
			'fecha_de_creacion' => 
			array (
				'name' => 'fecha_de_creacion',
				'type' => 'label',
			),
			'usr_id' => 
			array (
				'name' => 'usr_id',
				'type' => 'label',
			),
			'es_publica' => 
			array (
				'name' => 'es_publica',
				'type' => 'list',
				'options'=>array(0=>'NO',1=>'SI'),
			),
			'fuente_de_datos' => 
			array (
				'name' => 'fuente_de_datos',
				'type' => 'label',
				'value' => '',
			),
		)
	),
	'edit_custom' => 
	array (
		'title' => 'edit_table_title',
		'type' => 'record',
		'actions' => 
		array (
			0 => 'all_b2l',
			1 => 'all_edit2',
			2 => 'all_delete',
		),
		'fields' => 
		array (
			'id' => 
			array (
				'name' => 'id',
				'type' => 'label',
			),
			'titulo' => 
			array (
				'name' => 'titulo',
			),
		),
	),
	'list_all' => 
	array (
		'help' => 'list_all',
		'title' => 'table_plural',
		'type' => 'table',
		'restrict' => 'usr_id=\''.ssid().'\' or es_publica=1',
		'side_actions' => 
		array (
			'all_run',
			'all_edit',
			'all_delete',
		),
		'down_actions' => 
		array (
			2 => 'all_new',
		),
		'fields' => 
		array (
			'id' => 
			array (
				'name' => 'id',
				'type' => 'label',
			),
			'titulo' => 
			array (
				'name' => 'titulo',
			),
			'fecha_de_creacion' => 
			array (
				'name' => 'fecha_de_creacion',
				'type' => 'date',
				'value' => '2000-01-01',
			),
			'usr_id' => 
			array (
				'name' => 'usr_id',
				'type' => 'number',
				'value' => '1',
			),
			'es_publica' => 
			array (
				'name' => 'es_publica',
				'type' => 'boolean',
				'value' => '0',
			),
			'fuente_de_datos' => 
			array (
				'name' => 'fuente_de_datos',
				'type' => 'text',
				'value' => '',
			),
		),
	),
);
?>
