<?php
# autogenerated on:2009-01-03 16:44:02 
# by user:Administrator ID:1, try not to hand edit too much
$std_views['userfilter']=array (
  'edit_custom' => 
  array (
    'title' => 'edit_table_title',
    'type' => 'record',
    'actions' => 
    array (
      0 => 'all_b2l',
      1 => 'all_edit2',
      2 => 'all_delete',
    ),
    'fields' => 
    array (
      'id' => 
      array (
        'name' => 'id',
        'type' => 'label',
      ),
      'sql_filter' => 
      array (
        'name' => 'sql_filter',
      ),
    ),
  ),
  'list_custom' => 
  array (
    'help' => 'list_all',
    'title' => 'table_plural',
    'type' => 'table',
    'side_actions' => 
    array (
      0 => 'all_edit',
      1 => 'all_delete',
    ),
    'down_actions' => 
    array (
      0 => 'all_delete_selected',
      1 => 'all_xls',
      2 => 'all_new',
    ),
    'fields' => 
    array (
      'id' => 
      array (
        'name' => 'id',
        'type' => 'label',
      ),
      'sql_filter' => 
      array (
        'name' => 'sql_filter',
      ),
    ),
  ),
);
?>