<?php
# autogenerated on:2014-08-13 02:27:43 
# by user:Administrator ID:1, try not to hand edit too much
$std_rel['activity']=array (
  'has' => 
  array (
    'question' => 'question',
    'completed_activity' => 'completed_activity',
  ),
  'belongs_to' => 
  array (
    'session' => 'session',
    'activity_type' => 'activity_type',
    'activity_status' => 'activity_status',
  ),
  'hbm' => 
  array (
    'session' => 'activity2session',
  ),
);
?>