<?php
# autogenerated on:2014-08-11 13:37:33 
# by user:Administrator ID:1, try not to hand edit too much
$std_rel['activity2session']=array (
  'has' => 
  array (
  ),
  'hbm' => 
  array (
  ),
  'belongs_to' => 
  array (
  ),
);
?>