<?php
# autogenerated on:2014-07-31 14:44:52 
# by user:Administrator ID:1, try not to hand edit too much
$std_rel['category']=array (
  'has' => 
  array (
    'question' => 'question',
  ),
  'hbm' => 
  array (
  ),
  'belongs_to' => 
  array (
  ),
);
?>