<?php
# autogenerated on:2014-08-13 02:27:43 
# by user:Administrator ID:1, try not to hand edit too much
$std_rel['completed_activity']=array (
  'has' => 
  array (
  ),
  'hbm' => 
  array (
  ),
  'belongs_to' => 
  array (
    'usr' => 'usr',
    'activity' => 'activity',
  ),
);
?>