<?php
# autogenerated on:2014-08-19 01:00:55 
# by user:Administrator ID:1, try not to hand edit too much
$std_rel['message']=array (
  'has' => 
  array (
  ),
  'hbm' => 
  array (
  ),
  'belongs_to' => 
  array (
  ),
);
?>