<?php
# autogenerated on:2014-07-31 14:44:52 
# by user:Administrator ID:1, try not to hand edit too much
$std_rel['question']=array (
  'has' => 
  array (
    'question_option' => 'question_option',
    'answer' => 'answer',
  ),
  'belongs_to' => 
  array (
    'activity' => 'activity',
    'category' => 'category',
  ),
);
?>