<?php
# autogenerated on:2014-08-11 13:37:33 
# by user:Administrator ID:1, try not to hand edit too much
$std_rel['session']=array (
  'has' => 
  array (
    'content' => 'content',
  ),
  'hbm' => 
  array (
    'usr' => 'usr2session',
    'activity' => 'activity2session',
  ),
);
?>
