<?php
# autogenerated on:2014-08-24 00:02:34 
# by user:Administrator ID:1, try not to hand edit too much
$std_rel['team']=array (
  'has' => 
  array (
  ),
  'hbm' => 
  array (
  ),
  'belongs_to' => 
  array (
  ),
);
?>