<?php
# autogenerated on:2014-08-27 07:41:22 
# by user:Administrator ID:1, try not to hand edit too much
$std_rel['user_tutorial']=array (
  'has' => 
  array (
  ),
  'hbm' => 
  array (
  ),
  'belongs_to' => 
  array (
    'usr' => 'usr',
  ),
);
?>