<?php
# autogenerated on:2014-08-27 07:41:22 
# by user:Administrator ID:1, try not to hand edit too much
$std_rel['usr']=array (
  'has' => 
  array (
    'log' => 'log',
    'completed_activity' => 'completed_activity',
    'user_tutorial' => 'user_tutorial',
  ),
  'hbm' => 
  array (
    'role' => 'usr2role',
    'session' => 'usr2session',
  ),
);
?>