<?php
# autogenerated on:2009-06-12 12:22:19 
# by user:Administrator ID:1, try not to hand edit too much
$std_fields['campo_de_agrupamiento']=array (
  'id' => 
  array (
    'name' => 'id',
    'type' => 'label',
  ),
  'nombre' => 
  array (
    'name' => 'nombre',
  ),
  'informe_id' => 
  array (
    'name' => 'informe_id',
    'type' => 'number',
    'value' => '1',
  ),
  'posicion' => 
  array (
    'name' => 'posicion',
    'type' => 'text',
    'value' => '1',
  ),
  'es_filtrable' => 
  array (
    'name' => 'es_filtrable',
    'type' => 'list',
    'value' => 'N',
    'options' => 
    array (
      'Y' => 'Y',
      'N' => 'N',
    ),
  ),
);
?>