<?php
# autogenerated on:2009-05-18 17:13:27 
# by user:Administrator ID:1, try not to hand edit too much
$std_fields['chart_type']=array (
  'id' => 
  array (
    'name' => 'id',
    'type' => 'label',
  ),
  'name' => 
  array (
    'name' => 'name',
    'type' => 'text',
  ),
);
?>