<?php
# autogenerated on:2009-05-19 18:11:49 
# by user:Administrator ID:1, try not to hand edit too much
$std_fields['columna']=array (
  'id' => 
  array (
    'name' => 'id',
    'type' => 'label',
  ),
  'informe_id' => 
  array (
    'name' => 'informe_id',
    'type' => 'number',
  ),
  'nombre' => 
  array (
    'name' => 'nombre',
    'type' => 'text',
  ),
  'titulo' => 
  array (
    'name' => 'titulo',
    'type' => 'text',
  ),
  'orden' => 
  array (
    'name' => 'orden',
    'type' => 'number',
    'value' => '1',
  ),
  'calculado' => 
  array (
    'name' => 'calculado',
    'type' => 'list',
    'options'=>array('0','1'),
    'value' => '0',

  ),
  'visible' => 
  array (
    'name' => 'visible',
    'type' => 'list',
    'options'=>array('0','1'),
    'value' => '1',
  ),
);
?>
