<?php

global $config,$mydir;

# autogenerated on:2009-05-18 17:13:28 
# by user:Administrator ID:1, try not to hand edit too much
$std_fields['drill_down_report']=array (
	'id' => 
	array (
		'name' => 'id',
		'type' => 'label',
	),
	'name' => 
	array (
		'name' => 'name',
		'type' => 'text',
	),
	'description' => 
	array (
		'name' => 'description',
		'type' => 'textarea',
	),
	'table_name' => 
	array (
		'name' => 'table_name',
		'type' => 'list',
		'options'=>$this->q2op("select 
			distinct(table_name) as table_name
		from 
			drill_down_auth,
			drill_down_auth2role 
		where 
			drill_down_auth.id = drill_down_auth_id and 
			role_id in (
					select role_id from usr2role where usr_id='".ssid()."')",
			
		'table_name',"table_name"),

		),
	);

?>
