<?php
# autogenerated on:2010-11-29 14:22:41 
# by user:Administrator ID:1, try not to hand edit too much
$std_fields['drill_down_auth2role']=array (
  'id' => 
  array (
    'name' => 'id',
    'type' => 'label',
  ),
  'drill_down_auth_id' => 
  array (
    'name' => 'drill_down_auth_id',
  ),
  'role_id' => 
  array (
    'name' => 'role_id',
  ),
);
?>