<?php
# autogenerated on:2009-05-11 12:56:33 
# by user:Administrator ID:1, try not to hand edit too much
$std_fields['fuente']=array (
  'id' => 
  array (
    'name' => 'id',
    'type' => 'label',
  ),
  'columna_id' => 
  array (
    'name' => 'columna_id',
    'type' => 'number',
  ),
  'campo' => 
  array (
    'name' => 'campo',
    'type' => 'text',
  ),
  'valor' => 
  array (
    'name' => 'valor',
    'type' => 'text',
  ),
  'campo_fuente' => 
  array (
    'name' => 'campo_fuente',
    'type' => 'text',
    'value' => '',
  ),
);
?>