<?php
# autogenerated on:2009-05-15 17:22:36 
# by user:Administrator ID:1, try not to hand edit too much
$std_fields['informe']=array (
  'id' => 
  array (
    'name' => 'id',
    'type' => 'label',
  ),
  'nombre' => 
  array (
    'name' => 'nombre',
    'type' => 'text',
  ),
  'titulo' => 
  array (
    'name' => 'titulo',
    'type' => 'text',
  ),
  'fuente_de_datos' => 
  array (
    'name' => 'fuente_de_datos',
    'type' => 'text',
  ),
  'descripcion' => 
  array (
    'name' => 'descripcion',
    'type' => 'textarea',
    'value' => '',
  ),
);
?>
