<?php
# autogenerated on:2009-01-03 15:48:28 
# by user:Administrator ID:1, try not to hand edit too much
$std_fields['userquery']=array (
  'id' => 
  array (
    'name' => 'id',
    'type' => 'label',
  ),
  'titulo' => 
  array (
    'name' => 'titulo',
  ),
  'fecha_de_creacion' => 
  array (
    'name' => 'fecha_de_creacion',
    'type' => 'date',
    'value' => '2000-01-01',
  ),
  'usr_id' => 
  array (
    'name' => 'usr_id',
    'type' => 'number',
    'value' => '1',
  ),
  'es_publica' => 
  array (
    'name' => 'es_publica',
    'type' => 'list',
    'options'=>array(0=>'NO',1=>'SI'),
    'value' => '0',
  ),
  'fuente_de_datos' => 
  array (
    'name' => 'fuente_de_datos',
    'type' => 'text',
    'value' => '',
  ),
  'sql_text' => 
  array (
    'name' => 'sql_text',
    'type' => 'textarea',
    'value' => '',
  ),
);
?>
