<?php
# autogenerated on:2009-01-03 16:59:12 
# by user:Administrator ID:1, try not to hand edit too much
$std_fields['userfilter']=array (
  'id' => 
  array (
    'name' => 'id',
    'type' => 'label',
  ),
  'sql_filter' => 
  array (
    'name' => 'sql_filter',
  ),
  'usr_id' => 
  array (
    'name' => 'usr_id',
    'type' => 'number',
    'value' => '1',
  ),
  'reporte' => 
  array (
    'name' => 'reporte',
    'type' => 'text',
    'value' => '1',
  ),
);
?>