<?php
# autogenerated on:2014-08-25 00:37:09 
# by user:Administrator ID:1, try not to hand edit too much
$i18n['activity']=array (
  'list_all' => '<br><br>[#_field_info]',
  'table_title' => 'Activity',
  'new_table_title' => 'Add Activity',
  'edit_table_title' => 'Edit Activity',
  'view_table_title' => 'View Activity',
  'table_gender' => 'M',
  'table_plural' => 'Activities',
  'fields' => 
  array (
    'id' => 'Id',
    'help_id' => '',
    'name' => 'Name',
    'help_name' => '',
    'activity_type_id' => 'Activity type',
    'help_activity_type_id' => '',
    'activity_status_id' => 'Activity status',
    'help_activity_status_id' => '',
    'is_team_activity' => 'is Team Activity',
    'help_is_team_activity' => '',
    'timer' => 'Time in Seconds',
    'help_timer' => '',
  ),
);
?>