<?php
# autogenerated on:2014-07-31 14:40:32 
# by user:Administrator ID:1, try not to hand edit too much
$i18n['activity_type']=array (
  'list_all' => '<br><br>[#_field_info]',
  'table_title' => 'Activity type',
  'new_table_title' => 'Add Activity type',
  'edit_table_title' => 'Edit Activity type',
  'view_table_title' => 'View Activity type',
  'table_gender' => 'M',
  'table_plural' => 'Activity types',
  'fields' => 
  array (
    'id' => 'Id',
    'help_id' => '',
    'name' => 'Name',
    'help_name' => '',
    'description' => 'Description',
    'help_description' => '',
    'activity_value' => 'Activity Value',
    'help_activity_value' => '',
  ),
);
?>