<?php
# autogenerated on:2014-08-11 13:37:33 
# by user:Administrator ID:1, try not to hand edit too much
$i18n['activity2session']=array (
  'list_all' => '<br><br>[#_field_info]',
  'table_title' => 'Activity in Session',
  'table_plural' => 'Activities in Session',
  'table_gender' => 'M',
  'new_table_title' => 'New Activity in Session',
  'edit_table_title' => 'Edit Activity in Session',
  'fields' => 
  array (
    'id' => 'Id',
    'help_id' => 'Id',
    'activity_id' => 'Activity',
    'help_activity_id' => ' ',
    'session_id' => 'Session',
    'help_session_id' => ' ',
  ),
);
?>
