<?php
# autogenerated on:2014-07-31 14:44:34 
# by user:Administrator ID:1, try not to hand edit too much
$i18n['category']=array (
  'list_all' => '<br><br>[#_field_info]',
  'table_title' => 'Category',
  'table_plural' => 'Categories',
  'table_gender' => 'M',
  'new_table_title' => 'Nuevo Category',
  'edit_table_title' => 'Editar Category',
  'fields' => 
  array (
    'id' => 'Id',
    'help_id' => 'Id',
    'name' => 'Name',
    'help_name' => 'Name',
  ),
);
?>