<?php
# autogenerated on:2014-08-26 21:36:06 
# by user:Administrator ID:1, try not to hand edit too much
$i18n['completed_activity']=array (
  'list_all' => '<br><br>[#_field_info]',
  'table_title' => 'Completed activity',
  'table_plural' => 'Completed Activities',
  'table_gender' => 'M',
  'new_table_title' => 'New Completed activity',
  'edit_table_title' => 'Edit Completed activity',
  'fields' => 
  array (
    'id' => 'Id',
    'help_id' => 'Id',
    'activity_date' => 'Activity date',
    'help_activity_date' => 'Activity date',
    'usr_id' => 'User',
    'help_usr_id' => '',
    'activity_id' => 'Activity',
    'help_activity_id' => '',
    'team' => 'Team',
    'help_team' => '',
  ),
);
?>