<?php
# autogenerated on:2014-08-19 01:05:46 
# by user:Administrator ID:1, try not to hand edit too much
$i18n['message']=array (
  'list_all' => '<br><br>[#_field_info]',
  'table_title' => 'Message',
  'table_plural' => 'Messages',
  'table_gender' => 'M',
  'new_table_title' => 'New Message',
  'edit_table_title' => 'Edit Message',
  'fields' => 
  array (
    'id' => 'Id',
    'help_id' => 'Id',
    'name' => 'Name',
    'help_name' => 'Name',
    'source' => 'Source',
    'help_source' => '',
    'destination' => 'Destination',
    'help_destination' => '',
    'body' => 'Body',
    'help_body' => '',
    'view_date' => 'View Date',
    'help_view_date' => '',
    'creation_date' => 'Creation Date',
    'help_creation_date' => '',
  ),
);
?>