<?php
# autogenerated on:2014-07-31 14:44:52 
# by user:Administrator ID:1, try not to hand edit too much
$i18n['question']=array (
  'list_all' => '<br><br>[#_field_info]',
  'table_title' => 'Question',
  'new_table_title' => 'Add Question',
  'edit_table_title' => 'Edit Question',
  'view_table_title' => 'View Question',
  'table_gender' => 'M',
  'table_plural' => 'Questions',
  'fields' => 
  array (
    'id' => 'Id',
    'help_id' => '',
    'name' => 'Name',
    'help_name' => '',
    'description' => 'Description',
    'help_description' => '',
    'activity_id' => 'Activity',
    'help_activity_id' => '',
    'category_id' => 'Category',
    'help_category_id' => '',
  ),
);
?>