<?php
# autogenerated on:2014-08-13 11:20:33 
# by user:Administrator ID:1, try not to hand edit too much
$i18n['question_option']=array (
  'list_all' => '<br><br>[#_field_info]',
  'table_title' => 'Question option',
  'new_table_title' => 'Add Question option',
  'edit_table_title' => 'Edit Question option',
  'view_table_title' => 'View Question option',
  'table_gender' => 'M',
  'table_plural' => 'Question options',
  'fields' => 
  array (
    'id' => 'Id',
    'help_id' => '',
    'name' => 'Name',
    'help_name' => '',
    'question_id' => 'Question',
    'help_question_id' => '',
    'is_correct' => 'is Correct',
    'help_is_correct' => '',
  ),
);
?>