<?php
# autogenerated on:2014-08-24 00:02:34 
# by user:Administrator ID:1, try not to hand edit too much
$i18n['team']=array (
  'list_all' => '<br><br>[#_field_info]',
  'table_title' => 'Team',
  'table_plural' => 'Teams',
  'table_gender' => 'M',
  'new_table_title' => 'New Team',
  'edit_table_title' => 'Edit Team',
  'fields' => 
  array (
    'id' => 'Id',
    'help_id' => 'Id',
    'name' => 'Name',
    'help_name' => 'Name',
  ),
);
?>
