<?php
# autogenerated on:2014-08-27 07:44:19 
# by user:Administrator ID:1, try not to hand edit too much
$i18n['user_tutorial']=array (
  'list_all' => '<br><br>[#_field_info]',
  'table_title' => 'User tutorial',
  'table_plural' => 'User Tutorials',
  'table_gender' => 'M',
  'new_table_title' => 'New User tutorial',
  'edit_table_title' => 'Edit User tutorial',
  'fields' => 
  array (
    'id' => 'Id',
    'help_id' => 'Id',
    'name' => 'Name',
    'help_name' => '',
    'usr_id' => 'User',
    'help_usr_id' => '',
  ),
);
?>
