<?php
# autogenerated on:2014-07-31 14:47:27 
# by user:Administrator ID:1, try not to hand edit too much
$i18n['usr2session']=array (
  'list_all' => '<br><br>[#_field_info]',
  'table_title' => 'User in Session',
  'new_table_title' => 'Add User in Session',
  'edit_table_title' => 'Edit User in Session',
  'view_table_title' => 'View User in Session',
  'table_gender' => 'M',
  'table_plural' => 'Users in Session',
  'fields' => 
  array (
    'id' => 'Id',
    'help_id' => '',
    'usr_id' => 'User',
    'help_usr_id' => '',
    'session_id' => 'Session',
    'help_session_id' => '',
  ),
);
?>