<?php
# autogenerated on:2009-05-15 15:41:12 
# by user:Administrator ID:1, try not to hand edit too much
$std_rel['campo_de_agrupamiento']=array (
  'has' => 
  array (
  ),
  'hbm' => 
  array (
  ),
  'belongs_to' => 
  array (
    'informe' => 'informe',
  ),
);
?>