<?php
# autogenerated on:2010-11-29 14:22:41 
# by user:Administrator ID:1, try not to hand edit too much
$std_rel['drill_down_auth2role']=array (
  'has' => 
  array (
  ),
  'hbm' => 
  array (
  ),
  'belongs_to' => 
  array (
  ),
);
?>