<?php
# autogenerated on:2009-05-15 15:41:12 
# by user:Administrator ID:1, try not to hand edit too much
$std_rel['informe']=array (
  'has' => 
  array (
    'columna' => 'columna',
    'campo_de_agrupamiento' => 'campo_de_agrupamiento',
  ),
  'belongs_to' => 
  array (
  ),
);
?>