<?php
# autogenerated on:2009-01-03 16:44:30 
# by user:Administrator ID:1, try not to hand edit too much
$std_rel['userfilter']=array (
  'has' => 
  array (
  ),
  'hbm' => 
  array (
  ),
  'belongs_to' => 
  array (
    'usr' => 'usr',
  ),
);
?>