<?php
# autogenerated on:2009-01-03 15:46:10 
# by user:Administrator ID:1, try not to hand edit too much
$std_rel['userquery']=array (
  'has' => 
  array (
  ),
  'hbm' => 
  array (
  ),
  'belongs_to' => 
  array (
    'usr' => 'usr',
  ),
);
?>