<?php
# autogenerated on:2009-06-12 12:22:19 
# by user:Administrator ID:1, try not to hand edit too much
$i18n['campo_de_agrupamiento']=array (
  'list_all' => '<br><br>[#_field_info]',
  'table_title' => 'Campo de agrupamiento',
  'table_plural' => 'Campos de agrupamiento',
  'table_gender' => 'M',
  'new_table_title' => 'Nuevo Campo de agrupamiento',
  'edit_table_title' => 'Editar Campo de agrupamiento',
  'fields' => 
  array (
    'id' => 'Id',
    'help_id' => 'Id',
    'nombre' => 'Nombre',
    'help_nombre' => 'Nombre',
    'informe_id' => 'Informe',
    'help_informe_id' => '',
    'posicion' => 'Posicion',
    'help_posicion' => '',
    'es_filtrable' => 'Es Filtrable',
    'help_es_filtrable' => '',
  ),
);
?>