<?php
# autogenerated on:2009-05-18 17:15:27 
# by user:Administrator ID:1, try not to hand edit too much
$i18n['chart_type']=array (
  'table_title' => 'Tipo de Grafico',
  'table_plural' => 'Tipos de Grafico',
  'new_table_title' => 'Nuevo Tipo de Grafico',
  'edit_table_title' => 'Editar Tipo de Grafico',
  'table_gender' => 'M',
  'fields' => 
  array (
    'id' => 'Id',
    'help_id' => ' ',
    'name' => 'Nombre',
    'help_name' => ' ',
  ),
);
?>