<?php
# autogenerated on:2009-05-19 18:11:49 
# by user:Administrator ID:1, try not to hand edit too much
$i18n['columna']=array (
  'table_title' => 'Columna',
  'table_plural' => 'Columnas',
  'new_table_title' => 'Nueva Columna',
  'edit_table_title' => 'Editar Columna',
  'table_gender' => 'F',
  'fields' => 
  array (
    'id' => 'Id',
    'help_id' => ' ',
    'informe_id' => 'Informe',
    'help_informe_id' => ' ',
    'nombre' => 'Nombre',
    'help_nombre' => ' ',
    'titulo' => 'Titulo',
    'help_titulo' => ' ',
    'orden' => 'Orden',
    'help_orden' => '',
    'calculado' => 'Calculado',
    'help_calculado' => '',
    'visible' => 'Visible',
    'help_visible' => '',
  ),
);
?>