<?php
# autogenerated on:2009-05-18 17:16:51 
# by user:Administrator ID:1, try not to hand edit too much
$i18n['data_field']=array (
  'table_title' => 'Campo de Datos',
  'table_plural' => 'Campos de Datos',
  'new_table_title' => 'Nuevo Campo de Datos',
  'edit_table_title' => 'Editar Campo de Datos',
  'table_gender' => 'M',
  'fields' => 
  array (
    'id' => 'Id',
    'help_id' => ' ',
    'drill_down_report_id' => 'Reporte Grafico',
    'help_drill_down_report_id' => ' ',
    'label' => 'Etiqueta',
    'help_label' => ' ',
    'expression' => 'Expresion',
    'help_expression' => ' ',
  ),
);
?>