<?php
# autogenerated on:2009-05-18 17:57:37 
# by user:Administrator ID:1, try not to hand edit too much
$i18n['dimension_field']=array (
  'table_title' => 'Campo de Dimension',
  'table_plural' => 'Campos de Dimension',
  'new_table_title' => 'Nuevo Campo de Dimension',
  'edit_table_title' => 'Editar Campo de Dimension',
  'table_gender' => 'M',
  'fields' => 
  array (
    'id' => 'Id',
    'help_id' => ' ',
    'drill_down_report_id' => 'Reporte Grafico',
    'help_drill_down_report_id' => ' ',
    'name' => 'Nombre',
    'help_name' => ' ',
    'label' => 'Etiqueta',
    'help_label' => ' ',
    'chart_type_id' => 'Tipo de Grafico',
    'help_chart_type_id' => ' ',
  ),
  'edit_all' => 'edit_all',
);
?>