<?php
# autogenerated on:2009-05-18 17:44:02 
# by user:Administrator ID:1, try not to hand edit too much
$i18n['drill_down_report']=array (
  'table_title' => 'Reporte Grafico',
  'form_all_run' => 'Ejecutar',
  'form_all_export' => 'XML',
  'table_plural' => 'Reportes Grafico',
  'new_table_title' => 'Nuevo Reporte Grafico',
  'edit_table_title' => 'Editar Reporte Grafico',
  'table_gender' => 'M',
  'fields' => 
  array (
    'id' => 'Id',
    'help_id' => ' ',
    'name' => 'Nombre',
    'help_name' => ' ',
    'description' => 'Descripcion',
    'help_description' => ' ',
    'table_name' => 'Nombre de Tabla',
    'help_table_name' => ' ',
  ),
  'list_all' => 'Graficos',
);
?>
