<?php
# autogenerated on:2010-11-29 14:24:00 
# by user:Administrator ID:1, try not to hand edit too much
$i18n['drill_down_auth2role']=array (
  'list_all' => '<br><br>[#_field_info]',
  'table_title' => 'Autorizacion por Rol',
  'table_plural' => 'Autorizaciones por Rol',
  'table_gender' => 'F',
  'new_table_title' => 'Nueva Autorizacion por Rol',
  'edit_table_title' => 'Editar Autorizacion por Rol',
  'fields' => 
  array (
    'id' => 'Id',
    'help_id' => 'Id',
    'drill_down_auth_id' => 'Autorizacion',
    'help_drill_down_auth_id' => ' ',
    'role_id' => 'Rol',
    'help_role_id' => ' ',
  ),
);
?>