<?php
# autogenerated on:2010-11-29 14:23:31 
# by user:Administrator ID:1, try not to hand edit too much
$i18n['drill_down_auth']=array (
  'list_all' => '<br><br>[#_field_info]',
  'table_title' => 'Autorizacion',
  'table_plural' => 'Autorizaciones',
  'table_gender' => 'M',
  'new_table_title' => 'Nueva Autorizacion',
  'edit_table_title' => 'Editar Autorizacion',
  'fields' => 
  array (
    'id' => 'Id',
    'help_id' => 'Id',
    'table_name' => 'Fuente de Datos',
    'help_table_name' => 'Table name',
  ),
);
?>