<?php
# autogenerated on:2009-05-11 12:56:33 
# by user:Administrator ID:1, try not to hand edit too much
$i18n['fuente']=array (
  'table_title' => 'Fuente',
  'table_plural' => 'Fuentes',
  'new_table_title' => 'Nueva Fuente',
  'edit_table_title' => 'Editar Fuente',
  'table_gender' => 'F',
  'fields' => 
  array (
    'id' => 'Id',
    'help_id' => ' ',
    'columna_id' => 'Columna',
    'help_columna_id' => ' ',
    'campo' => 'Campo',
    'help_campo' => ' ',
    'valor' => 'Valor',
    'help_valor' => ' ',
    'campo_fuente' => 'Campo Fuente',
    'help_campo_fuente' => '',
  ),
);
?>