<?php
# autogenerated on:2009-05-15 17:22:36 
# by user:Administrator ID:1, try not to hand edit too much
$i18n['informe']=array (
  'table_title' => 'Informe',
  'form_all_run' => 'Ejecutar',
  'table_plural' => 'Informes',
  'new_table_title' => 'Nuevo Informe',
  'edit_table_title' => 'Editar Informe',
  'table_gender' => 'M',
  'fields' => 
  array (
    'id' => 'Id',
    'help_id' => ' ',
    'nombre' => 'Nombre',
    'help_nombre' => ' ',
    'titulo' => 'Titulo',
    'help_titulo' => ' ',
    'grupo' => 'Grupo',
    'help_grupo' => 'campo que agrupa',
    'fuente_de_datos' => 'Fuente De Datos',
    'help_fuente_de_datos' => ' ',
    'descripcion' => 'Descripcion',
    'help_descripcion' => '',
  ),
  'list_all' => 'Informes',
  'informes' => 'Informes',
);
?>