<?php
# autogenerated on:2009-01-06 12:35:41 
# by user:Administrator ID:1, try not to hand edit too much
$i18n['userfilter']=array (
  'list_all' => '<br><br>[#_field_info]',
  'table_title' => 'Filtro de Consulta',
  'table_plural' => 'Filtros de Consulta',
  'table_gender' => 'M',
  'new_table_title' => 'Nuevo Filtro de Consulta',
  'edit_table_title' => 'Editar Filtro de Consulta',
  'fields' => 
  array (
    'id' => 'Id',
    'help_id' => 'Id',
    'sql_filter' => 'Filtro SQL',
    'help_sql_filter' => 'Sql filter',
    'usr_id' => 'Usuario',
    'help_usr_id' => '',
    'reporte' => 'Fuente de Datos',
    'help_reporte' => '',
  ),
);
?>