<?php
# autogenerated on:2009-01-03 15:48:28 
# by user:Administrator ID:1, try not to hand edit too much
$i18n['userquery']=array (
  'list_all' => '<br><br>[#_field_info]',
  'form_all_run' => 'Ejecutar',
  'table_title' => 'Consulta de Usuario',
  'table_plural' => 'Consultas de Usuario',
  'table_gender' => 'F',
  'new_table_title' => 'Nueva Consulta de Usuario',
  'edit_table_title' => 'Editar Consulta de Usuario',
  'fields' => 
  array (
    'id' => 'Id',
    'help_id' => 'Id',
    'titulo' => 'Titulo',
    'help_titulo' => 'Titulo',
    'fecha_de_creacion' => 'Fecha de Creacion',
    'help_fecha_de_creacion' => '',
    'usr_id' => 'Usuario de Creación',
    'help_usr_id' => '',
    'es_publica' => 'es Publica',
    'help_es_publica' => '',
    'fuente_de_datos' => 'Fuente de Datos',
    'help_fuente_de_datos' => '',
    'sql_text' => 'Sql',
    'help_sql_text' => '',
  ),
);
?>
